Añadios scripts para añadir extensiones a libreofficce, añadir usuarios al grupo vboxusers, adecuamos vx-chrome-extensiones y vx-chrome-extensions y modificamos obtener-resolucion-pantalla para devolver 16:9 o 4:3 sin ambigüedades

diff --git a/usr/bin/obtener-resolucion-pantalla b/usr/bin/obtener-resolucion-pantalla
--- a/usr/bin/obtener-resolucion-pantalla
+++ b/usr/bin/obtener-resolucion-pantalla
@@ -1,15 +1,28 @@
 #!/usr/bin/env bash
 
 ## Comprobamos que existe el archivo donde estan definidas las resoluciones
-if test -f /usr/share/vitalinux/resolucion-pantalla/resoluciones-pantalla.txt ; then
-	# echo "Ok ... exite el archivo de definición de Resoluciones ..."
-	RESOLUTIONS="/usr/share/vitalinux/resolucion-pantalla/resoluciones-pantalla.txt"
-else
-	echo "Error ... no exite el archivo de definición de Resoluciones ..."
-	exit 1
-fi
+# if test -f /usr/share/vitalinux/resolucion-pantalla/resoluciones-pantalla.txt ; then
+#     # echo "Ok ... exite el archivo de definición de Resoluciones ..."
+#     RESOLUTIONS="/usr/share/vitalinux/resolucion-pantalla/resoluciones-pantalla.txt"
+# else
+#     echo "Error ... no exite el archivo de definición de Resoluciones ..."
+#     exit 1
+# fi
 
-xrandr -q 2> /dev/null | grep -Po 'current\s*\K\d+\s*x\s*\d+' | sed 's/ *x */ /' | tr -s " " ":" > /tmp/resolucion-pantalla
-resolucionx=$(cat /tmp/resolucion-pantalla | cut -d":" -f1)
-resoluciony=$(cat /tmp/resolucion-pantalla | cut -d":" -f2)
-grep "$resolucionx" "$RESOLUTIONS" | grep "$resoluciony" | awk -F" " '{print $2}'
+if vx-funcs-bash vx-detectar_gui ; then
+    RESOLUCIONGRAF="$(xrandr -q 2> /dev/null | grep -Po 'current\s*\K\d+\s*x\s*\d+' | sed 's/ *x */ /' | tr -s " " ":" | head -1)"
+else
+    # Es necesario ser root para suplantar al usuario gráfico y conocer la resolución:
+    # Si no se puede consultar por defecto se devuelve 16:9
+    [[ "$(whoami)" != "root" ]] && RESOLUCIONGRAF="16:9" || \
+    RESOLUCIONGRAF="$(export DISPLAY=:0 && su "$(vx-usuario-grafico)" -c "xrandr -q 2> /dev/null | grep -Po 'current\s*\K\d+\s*x\s*\d+' | sed 's/ *x */ /' | tr -s ' ' ':' | head -1" --login)"
+fi
+[[ "${RESOLUCIONGRAF}" =~ ^[0-9]+:[0-9]+$ ]] || RESOLUCIONGRAF="16:9"
+RESOLUCIONGRAFX=${RESOLUCIONGRAF%:*}
+RESOLUCIONGRAFY=${RESOLUCIONGRAF#*:}
+RESOL="$(echo "scale=4;(${RESOLUCIONGRAFX}/${RESOLUCIONGRAFY})" | bc)"
+RESOL4X3="$(echo "scale=4;(4/3)" | bc)"
+RESOL16X9="$(echo "scale=4;(16/9)" | bc)"
+
+RESULTADO="$(echo "scale=4; (sqrt((${RESOL16X9} - ${RESOL})^2) < sqrt((${RESOL4X3} - ${RESOL})^2))" | bc)"
+(( ${RESULTADO} == 1 )) && echo "16:9" || echo "4:3"
diff --git a/usr/bin/vx-firefox-extensiones b/usr/bin/vx-firefox-extensiones
--- a/usr/bin/vx-firefox-extensiones
+++ b/usr/bin/vx-firefox-extensiones
@@ -37,7 +37,7 @@ function instalarExtensionFirefox() {
         echo "=> Ok!! ${EXT_TYPE} firefox-extension \"${1}\" ${EXT_UID} ya esta instalada ..."
         return 0
     fi
-    if [ "$1" == "epubreader-2.0.7-fx.xpi" ]; then
+    if [ "$1" == "epubreader-2.0.9-fx.xpi" ]; then
         [ ! -f "${PATH_GLOBAL_FIREFOX}/{5384767E-00D9-40E9-B72F-9CC39D655D6F}.xpi" ] && \
         {
             cp "${EXT_URL}" "${PATH_GLOBAL_FIREFOX}/{5384767E-00D9-40E9-B72F-9CC39D655D6F}.xpi" && \
@@ -174,7 +174,12 @@ shift
 
 BASEDIR="/usr/share/vitalinux/firefox-extensions"
 FICH_LISTA_EXTENSIONES="${BASEDIR}/firefox-extensiones-listado"
-[ -f "${FICH_LISTA_EXTENSIONES}" ] && . "${FICH_LISTA_EXTENSIONES}"
+[ -f "${FICH_LISTA_EXTENSIONES}" ] && \
+. "${FICH_LISTA_EXTENSIONES}" || \
+{
+    echo "=> ¡¡Problemas!! No hay listado de extensiones disponible: ${FICH_LISTA_EXTENSIONES}" ;
+    exit 1
+}
 # Generamos una lista con los nombres de todas las extensiones disponibles:
 EXTENSIONES_DISPONIBLES=()
 for LINEA in $(sed -n "/^[^#].*=/p" "${FICH_LISTA_EXTENSIONES}") ; do
@@ -215,7 +220,7 @@ until [ -z "${1}" ] ; do
 done
 
 (( ${FALLOINS} == 1 )) && \
-echo "=> ¡¡Error!! La isntalación de alguna extensión de firefox ha dada problemas" && \
+echo "=> ¡¡Error!! La fallado la instalación de alguna extensión de firefox" && \
 exit 1
 
 (( ${FALLODES} == 1 )) && \
