Adaptando y mejorando scripts

diff --git a/usr/bin/vx-conf-soft-pdf-okular b/usr/bin/vx-conf-soft-pdf-okular
--- a/usr/bin/vx-conf-soft-pdf-okular
+++ b/usr/bin/vx-conf-soft-pdf-okular
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+EJECUTOR="$(whoami)"
+[ "${EJECUTOR}" != "root" ] && \
+echo "=> Error!! Debes ser root para configurar okular como visor PDF predeterminado." && \
+exit 1
+
 if [[ -f "/usr/bin/okular" && -x "/usr/bin/crudini" ]] ; then
     
     # El lanzador de okular no es el mismo en vx-14 que en vx-18:
@@ -7,37 +12,44 @@ if [[ -f "/usr/bin/okular" && -x "/usr/bin/crudini" ]] ; then
     [ -f "/usr/share/applications/org.kde.okular.desktop" ] && FICHDESKTOP="okularApplication_pdf.desktop"
     # [ -f "/usr/share/applications/org.kde.okular.desktop" ] && FICHDESKTOP="org.kde.okular.desktop"
     
-    echo "=> Configurando lanzador de okular como aplicación preferente para abrir PDFs: ${FICHDESKTOP}"
+    echo "=> Okular como aplicación preferente para abrir PDFs: ${FICHDESKTOP}"
     # Por defecto creamos el mime para los esqueletos de los nuevos usuarios:
     # crudini creara la sección o parámetro en caso de no existir, asignando el valor indicado
-    FICH="/etc/skel/.local/share/applications/mimeapps.list"
-    if [ -f "${FICH}" ] ; then
-        for SECCION in "Default Applications" "Added Associations" ; do
-            crudini --set "${FICH}" "${SECCION}" "application/pdf" "${FICHDESKTOP}" && \
-            echo "=> Okular configurado: \"${SECCION}\" \"application/pdf\" ${FICH}"
-        done
-    fi
     
-    # Si ya tenemos mimes personalizados definidos en los usuarios, los modificamos:
+    # Almacenaremos en un array los ficheros que se verán afectados:
+    # 1) Skel: /etc/skel/.local/share/applications/mimeapps.list
+    # 2) A nivel global: /usr/share/applications/mimeapps.list
+    # 3) mimes personalizados definidos en los usuarios
+    declare -a FICHEROS
+    declare -a MODIFICADOS
+    FICHEROS=( "/etc/skel/.local/share/applications/mimeapps.list" "/usr/share/applications/mimeapps.list" )
     for USUDIR in $(vx-home-usuarios-graficos) ; do
         FICH="${USUDIR}/.local/share/applications/mimeapps.list"
         if [ -f "${FICH}" ]; then
-            # sed -i '/pdf/d' ${USUDIR}/.local/share/applications/mimeapps.list
-            for SECCION in "Default Applications" "Added Associations" ; do
-                crudini --set "${FICH}" "${SECCION}" "application/pdf" "${FICHDESKTOP}" && \
-                echo "=> Okular configurado: \"${SECCION}\" \"application/pdf\" ${FICH}"
-            done
+            FICHEROS+=("${FICH}")
         fi
     done
     
-    # A nivel global del sistema podemos modificar dos ficheros:
-    # /etc/xdg/lubuntu/applications/defaults.list
-    # O también: /usr/share/applications/mimeapps.list
-    # Nos decantamos por éste último
-    GLOBALMIMEFILE="/usr/share/applications/mimeapps.list"
-    if [ -f $GLOBALMIMEFILE ] ; then
-        SECCION="Default Applications"
-        crudini --set "${GLOBALMIMEFILE}" "${SECCION}" "application/pdf" "${FICHDESKTOP}" && \
-        echo "=> Okular configurado: \"${SECCION}\" \"application/pdf\" ${GLOBALMIMEFILE}"
-    fi
+    for FICH in ${FICHEROS[@]} ; do
+        if [ -f "${FICH}" ] ; then
+            CAMBIO="false"
+            for SECCION in "Default Applications" "Added Associations" ; do
+                VALOR="$(crudini --get "${FICH}" "${SECCION}" "application/pdf")"
+                if [[ "${VALOR}" != "${FICHDESKTOP}" ]] ; then
+                    crudini --set "${FICH}" "${SECCION}" "application/pdf" "${FICHDESKTOP}" && \
+                    CAMBIO="true"
+                fi
+            done
+            ${CAMBIO} && MODIFICADOS+=("${FICH}")
+        fi
+    done
+    
+    MENSAJE="=> Okular configurado: "
+    (( ${#MODIFICADOS[@]} == 0 )) && \
+    MENSAJE+="Ya esta todo configurado" || \
+    MENSAJE+="\n\tSecciones: \"Default Applications\" \"Added Associations\" Valor: \"application/pdf\"\n\tFicheros: ${MODIFICADOS[*]}"
+    
+    echo -e "${MENSAJE}"
 fi
+
+exit 0
