Mejoramos y añadimos scripts

diff --git a/usr/bin/vx-eliminar-ficheros-conf-personales b/usr/bin/vx-eliminar-ficheros-conf-personales
--- a/usr/bin/vx-eliminar-ficheros-conf-personales
+++ b/usr/bin/vx-eliminar-ficheros-conf-personales
@@ -1,4 +1,5 @@
 #!/bin/bash
+# Ultima modificación: [arturo@2020-4-1]
 
 <<INFO
 
@@ -18,57 +19,119 @@
 ~/.config/lxpanel/default/panels/panel
 ~/.config/libfm/libfm.conf
 ~/.config/lxterminal/lxterminal.conf
+~/.config/albert
 
 # Se eliminan todos, a excepción del desktop-items-0.conf que crea los elementos virtuales
 # del Escritorio: papelera, Documentos, etc.
 
 INFO
 
-ERRORES=0
-USER="$(whoami)"
-if test "${USER}" == "root" ; then
-	for USUARIO in $(vx-usuarios-graficos) ; do
+FICHFUNCS="/usr/bin/vx-funcs-bash"
+[ -f "${FICHFUNCS}" ] && . "${FICHFUNCS}"
 
-		HOMEUSU="$(getent passwd "${USUARIO}" | cut -d":" -f6)"
-		for DIR in ".config/openbox" \
-			".config/lxsession" \
-			".config/pcmanfm" \
-			".config/lxpanel" \
-			".config/libfm" \
-			".config/lxterminal" ; do
-			if test -d "${HOMEUSU}/${DIR}" ; then
-				if ! rm -Rf "${HOMEUSU}/${DIR}" ; then
-					ERRORES=1
-					echo "ERROR: No se ha podido eliminar ${HOMEUSU}/${DIR} ..."
-				else
-					echo "OK: Se ha eliminado ${HOMEUSU}/${DIR} ..."
-				fi
-			fi
-		done
+EJECUTOR="$(whoami)"
 
-		# Copiamos desde el skel los archivos de configuración que no se autogeneran al iniciar sesión gráfica:
-		## ~/.config/pcmanfm/lubuntu/desktop-items-0.conf
-		## ~/.config/lxpanel/Lubuntu/panels/panel
-		## ~/.config/lxpanel/default/panels/panel
-		for DIR in ".config/pcmanfm" \
-			".config/lxpanel" ; do
-				if ! su "${USUARIO}" \
-					-c 'rsync -ahv /etc/skel/'${DIR}' '${HOMEUSU}'/.config' \
-					--login &> /dev/null ; then
-					ERRORES=1
-					echo "ERROR: Problema al copiar /etc/skel/${DIR} en ${HOMEUSU} ..."
-				else
-					echo "OK: copiado /etc/skel/${DIR} en ${HOMEUSU} ..."
-				fi
-		done
-		
-	done
-	#if test "${ERRORES}" -eq 0 ; then
-	#	exit 0
-	#else
-	#	exit 1
-	#fi
-else
-	echo "=> Problema: Debes usuario \"root\" para poder ejecutar este script ..."
-	exit 1
-fi
+# 1) Preparamos la auditoria del servicio:
+LOG="vx-eliminar-ficheros-conf-personales.log"
+vx-log_xsession -o "${LOG}"
+
+# Regeneramos los ficheros de configuración personales de los usuarios:
+# 2.1) Si no se pasan parámetros y lo llama el usuario root se regeneran todos los usuarios gráficos
+# 2.2) Si no se pasan parámetros y no lo llama el usuario root se regenera los del usuario gráfico actual
+# 2.3) Si se le pasan ususarios como parámetros se regeneran únicamente los de esos usuarios
+# if [[ ! -z "${1}" && "${EJECUTOR}" == "root" ]] ; then
+#     LISTA_USUARIOS=("${@}")
+#     elif [[ "${EJECUTOR}" == "root" ]] ; then
+#     LISTA_USUARIOS=($(vx-usuarios-graficos))
+# else
+#     LISTA_USUARIOS=("${EJECUTOR}")
+# fi
+
+# Los parámetros recibidos para determinar la lista de usuarios afectados puede ser:
+# 1) -ug => devolvería el usuario gráfico actual
+# 2) -u usu1,usu2,usu3,... => devolvería la lista de que usuarios indicados son reales
+# 3) -g grupo1,grupo2,... => devolvería la lista de que usuarios forman parte de esos grupos
+# 4) usu1 usu2 usu3 ... => devolvería la lista de usuarios indicados que son reales
+# 5) [sin parámetros] => devolvería la lista de todos los usuarios gráficos si el ejecutor es root, o el usuario que ejecuta si no es root
+LISTA_USUARIOS=($(vx-funcs-users vx-obtener_lista_usuarios "${@}"))
+
+vx-colorear_echo "magenta" "[$(vx-fecha)] Eliminación Ficheros Configuración usuarios: ${LISTA_USUARIOS[*]}"
+
+for USUARIO in ${LISTA_USUARIOS[@]} ; do
+    # Comprobamos que el usuario existe y cual es su HOME:
+    # vx-funcs-users vx-check_exit_users "${USU}" && \
+    # HOMEUSU="$(vx-home-usuario-grafico "${USUARIO}")" || \
+    # continue
+    
+    HOMEUSU="$(vx-home-usuario-grafico "${USUARIO}")"
+    
+    getent group "${USUARIO}" > /dev/null 2>&1 && \
+    PROPIETARIO="${USUARIO}:${USUARIO}" || \
+    PROPIETARIO="${USUARIO}"
+    
+    vx-colorear_echo "azul" "=> Eliminando Ficheros de Configuración: ${USUARIO}"
+    
+    for DIR in ".config/openbox" \
+    ".config/lxsession" \
+    ".config/pcmanfm" \
+    ".config/lxpanel" \
+    ".config/libfm" \
+    ".config/lxterminal" ; do
+        if [ -d "${HOMEUSU}/${DIR}" ] ; then
+            if ! rm -Rf "${HOMEUSU}/${DIR}" ; then
+                vx-colorear_echo "rojo" "=> ERROR: No se ha podido eliminar ${HOMEUSU}/${DIR} ..."
+            else
+                vx-colorear_echo "verde" "=> OK: Se ha eliminado ${HOMEUSU}/${DIR} ..."
+            fi
+        fi
+    done
+    
+    # Copiamos desde el skel los archivos de configuración que no se autogeneran al iniciar sesión gráfica:
+    ## ~/.config/pcmanfm/lubuntu/desktop-items-0.conf
+    ## ~/.config/lxpanel/Lubuntu/panels/panel
+    ## ~/.config/lxpanel/default/panels/panel
+    for DIR in ".config/pcmanfm" \
+    ".config/lxpanel" ; do
+        # if ! su "${USUARIO}" \
+        # -c 'rsync -ahv /etc/skel/'${DIR}' '${HOMEUSU}'/.config' \
+        # --login &> /dev/null ; then
+        #     ERRORES=1
+        #     echo "ERROR: Problema al copiar /etc/skel/${DIR} en ${HOMEUSU} ..."
+        # else
+        #     echo "OK: copiado /etc/skel/${DIR} en ${HOMEUSU} ..."
+        # fi
+        [[ ! -d "/etc/skel/${DIR}" ]] && continue
+        if rsync --delete -ah --chown="${PROPIETARIO}" "/etc/skel/${DIR}/" "${HOMEUSU}/${DIR}" ; then
+            vx-colorear_echo "verde" "=> OK: copiado /etc/skel/${DIR}/ en ${HOMEUSU}/${DIR}"
+        else
+            vx-colorear_echo "rojo" "=> ERROR: Problema al copiar /etc/skel/${DIR} en ${HOMEUSU}/${DIR}"
+        fi
+        
+    done
+    
+    # Sincronizamos Albert Launcher:
+    if [ -d "/etc/skel/.config/albert" ] ; then
+        # if ! su "${USUARIO}" \
+        # -c 'rsync -ahv --delete --exclude core.db /etc/skel/.config/albert '${HOMEUSU}'/.config' \
+        # --login &> /dev/null ; then
+        #     ERRORES=1
+        #     echo "ERROR: Problema al copiar Albert en ${HOMEUSU} ..."
+        # else
+        #     echo "OK: copiado Albert en ${HOMEUSU} ..."
+        # fi
+        
+        DIR=".config/albert"
+        if rsync -ah --delete --chown="${PROPIETARIO}" --exclude "core.db" "/etc/skel/${DIR}/" "${HOMEUSU}/${DIR}" ; then
+            vx-colorear_echo "verde" "=> OK: copiado /etc/skel/${DIR}/ en ${HOMEUSU}/${DIR}"
+        else
+            vx-colorear_echo "rojo" "=> ERROR: Problema al copiar /etc/skel/${DIR}/ en ${HOMEUSU}/${DIR}"
+        fi
+    else
+        vx-colorear_echo "rojo" "=> Warning: No hay configuración de Albert Launcher"
+    fi
+    
+    vx-colorear_echo "azul" "=> Terminada eliminación Ficheros de Configuración: ${USUARIO}"
+    
+done
+
+exit 0
diff --git a/usr/bin/vx-funcs-users b/usr/bin/vx-funcs-users
--- a/usr/bin/vx-funcs-users
+++ b/usr/bin/vx-funcs-users
@@ -1,29 +1,117 @@
 #!/bin/bash
+# Ultima modificación: [arturo@2020-4-1]
 
 FICHVARS="/etc/default/vx-dga-variables/vx-dga-variables-general.conf"
 [ -f "${FICHVARS}" ] && . "${FICHVARS}"
 
 USUARIOGRAFICO="$(vx-usuario-grafico)"
 
-function vx-help-funcs-users() {
-    FICHFUNCS="/usr/bin/vx-funcs-users"
+function vx-obtener_lista_usuarios() {
+    # Si NºParametros=0 y Ejecutor=root: devuelve la lista completa de usuarios gráficos
+    # Si NºParametros=0 y Ejecutor!=root: devuelve el ejecutor que ha llamado a la función
+    # Si NºParametros!=0 y Ejecutor=root:
+    # # Si primer parámetro es "-ug": devuelve el usuario gráfico
+    # # Si 1parámetro es "-u" y 2parametro "usu1,usu2,...": devuelve la lista de usuarios pasados sin comas
+    # # Si 1parámetro es "-g" y 2parametro "grupo1,grupo2,...": devuelve la lista de usuarios sin comas pertenecientes a los grupos indicados
+    # # Si no es ninguna de las anteriores comprueba la lista de usuarios pasada por parámetros y devuelve la lista de usarios reales
+    local USUARIO="$(whoami)"
+    local LISTA_USUARIOS=()
+    if [[ ! -z "${1}" && "${USUARIO}" == "root" && "${1}" == "-ug" ]] ; then
+        LISTA_USUARIOS=("$(vx-usuario-grafico)")
+        elif [[ ! -z "${1}" && "${USUARIO}" == "root" && "${1}" == "-u" ]] ; then
+        # -u: Se pasa como segundo parámetro una lista de usuarios separados por comas:
+        for USU in ${2//,/ } ; do
+            vx-check_exit_users "${USU}" && \
+            LISTA_USUARIOS+=("${USU}")
+        done
+        elif [[ ! -z "${1}" && "${USUARIO}" == "root" && "${1}" == "-g" ]] ; then
+        # -g: Se pasa como segundo parámetro una lista de grupos separados por comas:
+        LISTA_GRUPOS=(${2//,/ })
+        for GRUPO in ${LISTA_GRUPOS[@]} ; do
+            vx-funcs-users vx-check_exit_groups "${GRUPO}" && \
+            LISTA_USUARIOS+=($(members "${GRUPO}"))
+        done
+        elif [[ ! -z "${1}" && "${USUARIO}" == "root" ]] ; then
+        for USU in ${@} ; do
+            vx-check_exit_users "${USU}" && \
+            LISTA_USUARIOS+=("${USU}")
+        done
+        elif [[ "${USUARIO}" == "root" ]] ; then
+        LISTA_USUARIOS=($(vx-usuarios-graficos))
+    else
+        LISTA_USUARIOS=("${USUARIO}")
+    fi
+    echo "$(vx-funcs-bash vx-lista_uniq ${LISTA_USUARIOS[@]})"
+}
+
+function vx-conf_idioma_usuario() {
+    # Require 3 parametros: usuario, lenguaje (en) y formatslocale (en_GB.UTF-8)
+    local USUARIO="${1}"
+    ! vx-check_exit_users && \
+    echo "=> ¡¡Error!! El usuario no existe: ${USUARIO}" && exit 1
+    local HOMEUSU="$(vx-home-usuario-grafico "${USUARIO}")"
+    local LENGUAJE="${2}"
+    local FORMATOLOCAL="${3}"
+    # Establecer el idioma elegido por defecto del lightdm:
+      cat > "/var/lib/AccountsService/users/${USUARIO}" <<EOF
+[User]
+#Language=en
+Language=${LENGUAJE}
+#FormatsLocale=en_GB.UTF-8
+FormatsLocale=${FORMATOLOCAL}
+XSession=Lubuntu
+SystemAccount=false
+EOF
+    # Establecer el idioma elegido en el PAM environment:
+      cat > "${HOMEUSU}/.pam_environment" <<EOF
+LANGUAGE=${LENGUAJE}
+LANG=${FORMATOLOCAL}
+LC_TIME=${FORMATOLOCAL}
+EOF
+    # Ajustamos el propietario del pam_environment:
+    chown "${USUARIO}".sudo "${HOMEUSU}/.pam_environment"
+    
+    return 0
+}
+
+function vx-check_exit_users() {
+    local USERSOK="true"
+    until [ -z "${1}" ] ; do
+        ! getent passwd "${1}" > /dev/null 2>&1 && USERSOK="false"
+        shift
+    done
+    "${USERSOK}" && return 0 || return 1
+}
+
+function vx-check_exit_groups() {
+    local GRUPOSOK="true"
+    until [ -z "${1}" ] ; do
+        ! getent group "${1}" > /dev/null 2>&1 && GRUPOSOK="false"
+        shift
+    done
+    "${GRUPOSOK}" && return 0 || return 1
+}
+
+function vx-funcs-users-help() {
+    local FICHFUNCS="/usr/bin/vx-funcs-users"
     for FUNCION in $(sed -n "s/^function \(.*\)().*/\1/gp" "${FICHFUNCS}") ; do
         [[ "${1}" != "--help" ]] && echo "${FUNCION} --help" && continue
         [[ "${FUNCION}" != "vx-help-funcs-users" ]] && \
         echo ":== Función ${FUNCION} ==:" && \
         "${FUNCION}" --help
+        echo "--"
     done
 }
 
 function vx-resetear_usuarios() {
-    AYUDA="# Función: Elimina todos los usuarios a excepción de los usuarios pasados por parametro"
+    local AYUDA="# Función: Elimina todos los usuarios a excepción de los usuarios pasados por parametro"
     AYUDA+="\n# Uso: vx-resetear_usuarios [usu1] [usu2] ..."
     AYUDA+="\n# Uso: vx-resetear_usuarios profesor dga"
     [ "${1}" == "--help" ] && \
     echo -e "${AYUDA}" && return 0
     
-    LISTA_USUARIOS_A_CONSERVAR=(${*})
-    USUARIOS_A_BORRAR=($(vx-usuarios-graficos))
+    local LISTA_USUARIOS_A_CONSERVAR=(${*})
+    local USUARIOS_A_BORRAR=($(vx-usuarios-graficos))
     # echo "Todos usuarios gráficos actuales: ${USUARIOS_A_BORRAR[@]}"
     # echo "Usuarios a conservar: ${LISTA_USUARIOS_A_CONSERVAR[@]}"
     
@@ -50,7 +138,7 @@ function vx-resetear_usuarios() {
 }
 
 function vx-grupo_primario() {
-    AYUDA="# Función: Asocia a un usuario un grupo primario de pertenencia"
+    local AYUDA="# Función: Asocia a un usuario un grupo primario de pertenencia"
     AYUDA+="\n# Uso: vx-grupo_primario [usuario] [grupo] ... ..."
     AYUDA+="\n# Uso: vx-grupo_primario profesories sudo alumno1A alumno"
     [ "${1}" == "--help" ] && \
@@ -351,12 +439,14 @@ function vx-borrar_usuario() {
     USUARIOS="$*"
     for USUARIO in ${USUARIOS} ; do
         if test "${USUARIOGRAFICO}" != "${USUARIO}" ; then
-            ( getent passwd "${USUARIO}" > /dev/null 2>&1 ) && \
-            /usr/sbin/userdel -fr "${USUARIO}"
+            if getent passwd "${USUARIO}" > /dev/null 2>&1 ; then
+                /usr/sbin/userdel -fr "${USUARIO}" && \
+                echo "=> Se ha eliminado el usuario: ${USUARIO}"
+            else
+                echo "=> El usuario ${USUARIO} no existe en el sistema ..."
+            fi
         fi
     done
 }
-
-
 
 "$@" 2> /dev/null
diff --git a/usr/bin/vx-regenerar-directorios-usuarios-cli b/usr/bin/vx-regenerar-directorios-usuarios-cli
--- a/usr/bin/vx-regenerar-directorios-usuarios-cli
+++ b/usr/bin/vx-regenerar-directorios-usuarios-cli
@@ -1,63 +1,48 @@
 #!/bin/bash
+# Ultima modificación: [arturo@2020-4-1]
+# Proyecto Software Libre DGA
 
-#Diseñado por Arturo Martín
-#Proyecto Software Libre DGA
+FICHFUNCS="/usr/bin/vx-funcs-bash"
+[ -f "${FICHFUNCS}" ] && . "${FICHFUNCS}"
 
-EJECUTOR=$(whoami)
+EJECUTOR="$(whoami)"
 
-function log_xsession(){
-    #
-    # Funcion que audita el proceso. Si no se pasa como parámetro el nombre del fichero, dejará un log en /tmp
-    # Se auditará en /var/log/vitalinux en el archivo indicado: log_xsession -o nombre_fichero
-    #
-    while getopts 'o:' OPT; do
-        case ${OPT} in
-            o) LOGFILE=${OPTARG};;
-        esac
-    done
-    
-    if [ "${LOGFILE}" ] ; then
-        if [ ! -d /var/log/vitalinux ]; then
-            mkdir -p /var/log/vitalinux
-        fi
-        LOGFILE="/var/log/vitalinux/${LOGFILE}"
-    else
-        LOGFILE="/tmp/logfile.regenerar-perfil-usuarios.log"
-    fi
-    
-    exec 2>&1
-    exec > >(tee -i "${LOGFILE}" )
-    
-}
+# 1) Preparamos la auditoria del servicio:
+LOG="vx-regenerar-directorios-perfil-usuarios.log"
+vx-log_xsession -o "${LOG}"
 
-log_xsession -o vx-regenerar-perfil-usuarios.log
+# Regeneramos el entorno de escritorio de los usuarios:
+# 2.1) Si no se pasan parámetros y lo llama el usuario root se regeneran todos los usuarios gráficos
+# 2.2) Si no se pasan parámetros y no lo llama el usuario root se regenera la del usuario gráfico actual
+# 2.3) Si se le pasan ususarios como parámetros se regeneran únicamente los de esos usuarios
+# if [[ ! -z "${1}" && "${EJECUTOR}" == "root" ]] ; then
+#     LISTA_USUARIOS=("${@}")
+#     elif [[ "${EJECUTOR}" == "root" ]] ; then
+#     LISTA_USUARIOS=($(vx-usuarios-graficos))
+# else
+#     LISTA_USUARIOS=("${EJECUTOR}")
+# fi
 
-if test "${EJECUTOR}" != "root" ; then
-    echo "Se requiren privilegios de \"root\" para lanzar Regenerar los perfiles de los usuarios ..."
-    exit 1
-fi
+# Los parámetros recibidos para determinar la lista de usuarios afectados puede ser:
+# 1) -ug => devolvería el usuario gráfico actual
+# 2) -u usu1,usu2,usu3,... => devolvería la lista de que usuarios indicados son reales
+# 3) -g grupo1,grupo2,... => devolvería la lista de que usuarios forman parte de esos grupos
+# 4) usu1 usu2 usu3 ... => devolvería la lista de usuarios indicados que son reales
+# 5) [sin parámetros] => devolvería la lista de todos los usuarios gráficos si el ejecutor es root, o el usuario que ejecuta si no es root
+LISTA_USUARIOS=($(vx-funcs-users vx-obtener_lista_usuarios "${@}"))
 
-echo "=> $(date) - Se va a Regenerar los perfiles de los usuarios del sistema ..."
+vx-colorear_echo "magenta" "[$(vx-fecha)] Regeneración directorios perfil de usuarios: ${LISTA_USUARIOS[*]}"
 
 # 1) Comenzamos regenerando el contenido del Escritorio y resto de directorios del perfil de los usuarios
-for USUARIO in $(vx-usuarios-graficos) ; do
-    echo ":=> Sincronizando directorios del usuario: ${USUARIO}"
-    HOMEUSUARIO="$(getent passwd "${USUARIO}" | cut -d":" -f6)"
-    # El directorio Escritorio se regenera a través del script vx-regenerar-entorno-escritorio-cli:
-    # BASE="/etc/skel/Escritorio/"
-    # if test -d "${BASE}" ; then
-    # 	for DIR in "Escritorio" "Desktop" "Bureau" "Schreibtisch" ; do
-    # 		if test -d "${HOMEUSUARIO}/${DIR}" ; then
-    # 			if su "${USUARIO}" \
-    # 				-c 'rsync --delete -rl '${BASE}' '${HOMEUSUARIO}'/'${DIR} \
-    # 				--login &> /dev/null ; then
-    # 				echo " --> OK: Se ha sincronizado el ${DIR} del usuario ${USUARIO} ..."
-    # 			else
-    # 				echo " --> ERROR: No se ha sincronizado el ${DIR} del usuario ${USUARIO} ..."
-    # 			fi
-    # 		fi
-    # 	done
-    # fi
+for USUARIO in ${LISTA_USUARIOS[@]} ; do
+    # Comprobamos que el usuario existe y cual es su HOME:
+    # vx-funcs-users vx-check_exit_users "${USU}" && \
+    # HOMEUSUARIO="$(vx-home-usuario-grafico "${USUARIO}")" || \
+    # continue
+    
+    HOMEUSUARIO="$(vx-home-usuario-grafico "${USUARIO}")"
+    
+    vx-colorear_echo "azul" "=> Regeneración de directorios del perfil: ${USUARIO}"
     
     #BASE="$(su "${USUARIO}" -c 'mktemp -d --tmpdir vx-sincro-directorios.XXXXXXXX' --login)"
     ## Definimos los distintos nombres de los directorios del perfil en los 4 idiomas principales:
@@ -79,17 +64,49 @@ for USUARIO in $(vx-usuarios-graficos) ; do
             for DIR in ${LISTA_DIR[*]} ; do
                 # echo "=> Se va a tratar de sincronizar el directorio: \"${DIR}\""
                 if test -d "${HOMEUSUARIO}/${DIR}" ; then
-                    if su "${USUARIO}" \
-                    -c 'rsync --delete -rl '${BASE}' '${HOMEUSUARIO}'/'${DIR} \
-                    --login > /dev/null 2>&1; then
-                        echo "==> OK: Se ha sincronizado el directorio ${DIR} del usuario ${USUARIO} ..."
+                    # if su "${USUARIO}" \
+                    # -c 'rsync --delete -rl '${BASE}' '${HOMEUSUARIO}'/'${DIR} \
+                    # --login > /dev/null 2>&1; then
+                    #     echo "==> OK: Se ha sincronizado el directorio ${DIR} del usuario ${USUARIO} ..."
+                    # else
+                    #     echo "==> ERROR: No se ha sincronizado el directorio ${DIR} del usuario ${USUARIO} ..."
+                    # fi
+                    getent group "${USUARIO}" > /dev/null 2>&1 && \
+                    PROPIETARIO="${USUARIO}:${USUARIO}" || \
+                    PROPIETARIO="${USUARIO}"
+                    if rsync --delete -ah --chown="${PROPIETARIO}" "${BASE}" "${HOMEUSUARIO}/${DIR}" ; then
+                        vx-colorear_echo "verde" " => OK: Sincronizado ${HOMEUSUARIO}/${DIR} del usuario: ${USUARIO} ..."
                     else
-                        echo "==> ERROR: No se ha sincronizado el directorio ${DIR} del usuario ${USUARIO} ..."
+                        vx-colorear_echo "rojo" " => ERROR: No sincronizado ${HOMEUSUARIO}/${DIR} del usuario: ${USUARIO} ..."
                     fi
                 fi
             done
         fi
         IFS=${SAVEIFS}
     done
+    
+    # Eliminamos el registro del Albert (core.db) y sus indexaciones que pudiera existir:
+    if [ -d "/etc/skel/.config/albert" ] ; then
+        # if ! su "${USUARIO}" \
+        # -c 'rsync -ahv --delete /etc/skel/.config/albert '${DIR}'/.config' \
+        # --login &> /dev/null ; then
+        #     ERRORES=1
+        #     echo "ERROR: Problema al copiar Albert en ${DIR} ..."
+        # else
+        #     echo "OK: copiado Albert en ${DIR} ..."
+        # fi
+        getent group "${USUARIO}" > /dev/null 2>&1 && \
+        PROPIETARIO="${USUARIO}:${USUARIO}" || \
+        PROPIETARIO="${USUARIO}"
+        if rsync -ah --delete --chown="${PROPIETARIO}" "/etc/skel/.config/albert" "${HOMEUSUARIO}/.config" ; then
+            vx-colorear_echo "verde" "=> OK: copiado /etc/skel/.config/albert en ${HOMEUSUARIO}/.config"
+        else
+            vx-colorear_echo "rojo" "=> ERROR: Problema al copiar /etc/skel/.config/albert en ${HOMEUSUARIO}/.config"
+        fi
+    else
+        vx-colorear_echo "rojo" "=> Warning: No hay configuración de Albert Launcher"
+    fi
+    
+    vx-colorear_echo "azul" "=> Terminada Regeneración Directorios del perfil: ${USUARIO}"
     
 done
