Añadimos y adaptamos multiples scripts para poder realizar las configuraciones indicadas en el Json asociado a cada centro

diff --git a/usr/bin/vx-eliminar-ficheros-conf-personales b/usr/bin/vx-eliminar-ficheros-conf-personales
--- a/usr/bin/vx-eliminar-ficheros-conf-personales
+++ b/usr/bin/vx-eliminar-ficheros-conf-personales
@@ -26,64 +26,86 @@
 INFO
 
 ERRORES=0
-USER="$(whoami)"
-if test "${USER}" == "root" ; then
-    for USUARIO in $(vx-usuarios-graficos) ; do
-        
-        HOMEUSU="$(getent passwd "${USUARIO}" | cut -d":" -f6)"
-        for DIR in ".config/openbox" \
-        ".config/lxsession" \
-        ".config/pcmanfm" \
-        ".config/lxpanel" \
-        ".config/libfm" \
-        ".config/lxterminal" ; do
-            if test -d "${HOMEUSU}/${DIR}" ; then
-                if ! rm -Rf "${HOMEUSU}/${DIR}" ; then
-                    ERRORES=1
-                    echo "ERROR: No se ha podido eliminar ${HOMEUSU}/${DIR} ..."
-                else
-                    echo "OK: Se ha eliminado ${HOMEUSU}/${DIR} ..."
-                fi
-            fi
-        done
-        
-        # Copiamos desde el skel los archivos de configuración que no se autogeneran al iniciar sesión gráfica:
-        ## ~/.config/pcmanfm/lubuntu/desktop-items-0.conf
-        ## ~/.config/lxpanel/Lubuntu/panels/panel
-        ## ~/.config/lxpanel/default/panels/panel
-        for DIR in ".config/pcmanfm" \
-        ".config/lxpanel" ; do
-            if ! su "${USUARIO}" \
-            -c 'rsync -ahv /etc/skel/'${DIR}' '${HOMEUSU}'/.config' \
-            --login &> /dev/null ; then
-                ERRORES=1
-                echo "ERROR: Problema al copiar /etc/skel/${DIR} en ${HOMEUSU} ..."
-            else
-                echo "OK: copiado /etc/skel/${DIR} en ${HOMEUSU} ..."
-            fi
-        done
-        
-        # Sincronizamos Albert Launcher:
-        if [ -d "/etc/skel/.config/albert" ] ; then
-            if ! su "${USUARIO}" \
-            -c 'rsync -ahv --delete --exclude core.db /etc/skel/.config/albert '${HOMEUSU}'/.config' \
-            --login &> /dev/null ; then
-                ERRORES=1
-                echo "ERROR: Problema al copiar Albert en ${HOMEUSU} ..."
-            else
-                echo "OK: copiado Albert en ${HOMEUSU} ..."
-            fi
-        else
-            echo "Warning: No hay configuración de Albert Launcher"
-        fi
-        
-    done
-    #if test "${ERRORES}" -eq 0 ; then
-    #	exit 0
-    #else
-    #	exit 1
-    #fi
+EJECUTOR="$(whoami)"
+
+# Regeneramos los ficheros de configuración personales de los usuarios:
+# 2.1) Si no se pasan parámetros y lo llama el usuario root se regeneran todos los usuarios gráficos
+# 2.2) Si no se pasan parámetros y no lo llama el usuario root se regenera los del usuario gráfico actual
+# 2.3) Si se le pasan ususarios como parámetros se regeneran únicamente los de esos usuarios
+if [[ ! -z "${1}" && "${EJECUTOR}" == "root" ]] ; then
+    LISTA_USUARIOS=("${@}")
+    elif [[ "${EJECUTOR}" == "root" ]] ; then
+    LISTA_USUARIOS=($(vx-usuarios-graficos))
 else
-    echo "=> Problema: Debes usuario \"root\" para poder ejecutar este script ..."
-    exit 1
+    LISTA_USUARIOS=("${EJECUTOR}")
 fi
+
+for USUARIO in ${LISTA_USUARIOS[@]} ; do
+    # Comprobamos que el usuario existe y cual es su HOME:
+    vx-funcs-users vx-check_exit_users "${USU}" && \
+    HOMEUSU="$(vx-home-usuario-grafico "${USUARIO}")" || \
+    continue
+    
+    for DIR in ".config/openbox" \
+    ".config/lxsession" \
+    ".config/pcmanfm" \
+    ".config/lxpanel" \
+    ".config/libfm" \
+    ".config/lxterminal" ; do
+        if test -d "${HOMEUSU}/${DIR}" ; then
+            if ! rm -Rf "${HOMEUSU}/${DIR}" ; then
+                ERRORES=1
+                echo "=> ERROR: No se ha podido eliminar ${HOMEUSU}/${DIR} ..."
+            else
+                echo "=> OK: Se ha eliminado ${HOMEUSU}/${DIR} ..."
+            fi
+        fi
+    done
+    
+    # Copiamos desde el skel los archivos de configuración que no se autogeneran al iniciar sesión gráfica:
+    ## ~/.config/pcmanfm/lubuntu/desktop-items-0.conf
+    ## ~/.config/lxpanel/Lubuntu/panels/panel
+    ## ~/.config/lxpanel/default/panels/panel
+    for DIR in ".config/pcmanfm" \
+    ".config/lxpanel" ; do
+        # if ! su "${USUARIO}" \
+        # -c 'rsync -ahv /etc/skel/'${DIR}' '${HOMEUSU}'/.config' \
+        # --login &> /dev/null ; then
+        #     ERRORES=1
+        #     echo "ERROR: Problema al copiar /etc/skel/${DIR} en ${HOMEUSU} ..."
+        # else
+        #     echo "OK: copiado /etc/skel/${DIR} en ${HOMEUSU} ..."
+        # fi
+        if rsync --delete -rl --chown="${USUARIO}" "/etc/skel/${DIR}" "${HOMEUSU}/.config" ; then
+            echo "=> OK: copiado /etc/skel/${DIR} en ${HOMEUSU}/.config"
+        else
+            echo "=> ERROR: Problema al copiar /etc/skel/${DIR} en ${HOMEUSU}/.config"
+        fi
+    done
+    
+    # Sincronizamos Albert Launcher:
+    if [ -d "/etc/skel/.config/albert" ] ; then
+        # if ! su "${USUARIO}" \
+        # -c 'rsync -ahv --delete --exclude core.db /etc/skel/.config/albert '${HOMEUSU}'/.config' \
+        # --login &> /dev/null ; then
+        #     ERRORES=1
+        #     echo "ERROR: Problema al copiar Albert en ${HOMEUSU} ..."
+        # else
+        #     echo "OK: copiado Albert en ${HOMEUSU} ..."
+        # fi
+        if rsync -ahv --delete --chown="${USUARIO}" --exclude "core.db" "/etc/skel/.config/albert" "${HOMEUSU}/.config" ; then
+            echo "OK: copiado /etc/skel/.config/albert en ${HOMEUSU}/.config"
+        else
+            echo "ERROR: Problema al copiar /etc/skel/.config/albert en ${HOMEUSU}/.config"
+        fi
+    else
+        echo "Warning: No hay configuración de Albert Launcher"
+    fi
+    
+done
+
+#if test "${ERRORES}" -eq 0 ; then
+#	exit 0
+#else
+#	exit 1
+#fi
diff --git a/usr/bin/vx-funcs-users b/usr/bin/vx-funcs-users
--- a/usr/bin/vx-funcs-users
+++ b/usr/bin/vx-funcs-users
@@ -5,6 +5,54 @@ FICHVARS="/etc/default/vx-dga-variables/vx-dga-variables-general.conf"
 
 USUARIOGRAFICO="$(vx-usuario-grafico)"
 
+function vx-conf_idioma_usuario() {
+    # Require 3 parametros: usuario, lenguaje (en) y formatslocale (en_GB.UTF-8)
+    USUARIO="${1}"
+    ! vx-check_exit_users && \
+    echo "=> ¡¡Error!! El usuario no existe: ${USUARIO}" && exit 1
+    HOMEUSU="$(vx-home-usuario-grafico "${USUARIO}")"
+    LENGUAJE="${2}"
+    FORMATOLOCAL="${3}"
+    # Establecer el idioma elegido por defecto del lightdm:
+      cat > "/var/lib/AccountsService/users/${USUARIO}" <<EOF
+[User]
+#Language=en
+Language=${LENGUAJE}
+#FormatsLocale=en_GB.UTF-8
+FormatsLocale=${FORMATOLOCAL}
+XSession=Lubuntu
+SystemAccount=false
+EOF
+    # Establecer el idioma elegido en el PAM environment:
+      cat > "${HOMEUSU}/.pam_environment" <<EOF
+LANGUAGE=${LENGUAJE}
+LANG=${FORMATOLOCAL}
+LC_TIME=${FORMATOLOCAL}
+EOF
+    # Ajustamos el propietario del pam_environment:
+    chown "${USUARIO}".sudo "${HOMEUSU}/.pam_environment"
+    
+    return 0
+}
+
+function vx-check_exit_users() {
+    USERSOK="true"
+    until [ -z "${1}" ] ; do
+        ! getent passwd "${1}" > /dev/null 2>&1 && USERSOK="false"
+        shift
+    done
+    "${USERSOK}" && return 0 || return 1
+}
+
+function vx-check_exit_groups() {
+    GRUPOSOK="true"
+    until [ -z "${1}" ] ; do
+        ! getent group "${1}" > /dev/null 2>&1 && GRUPOSOK="false"
+        shift
+    done
+    "${GRUPOSOK}" && return 0 || return 1
+}
+
 function vx-funcs-users-help() {
     FICHFUNCS="/usr/bin/vx-funcs-users"
     for FUNCION in $(sed -n "s/^function \(.*\)().*/\1/gp" "${FICHFUNCS}") ; do
diff --git a/usr/bin/vx-regenerar-directorios-usuarios-cli b/usr/bin/vx-regenerar-directorios-usuarios-cli
--- a/usr/bin/vx-regenerar-directorios-usuarios-cli
+++ b/usr/bin/vx-regenerar-directorios-usuarios-cli
@@ -3,7 +3,10 @@
 #Diseñado por Arturo Martín
 #Proyecto Software Libre DGA
 
-EJECUTOR=$(whoami)
+EJECUTOR="$(whoami)"
+LOG="vx-regenerar-directorios-perfil-usuarios.log"
+USUGRAF="$(vx-usuario-grafico)"
+HOMEUSUGRAF="$(vx-home-usuario-grafico "${EJECUTOR}")"
 
 function log_xsession(){
     #
@@ -17,47 +20,38 @@ function log_xsession(){
     done
     
     if [ "${LOGFILE}" ] ; then
-        if [ ! -d /var/log/vitalinux ]; then
-            mkdir -p /var/log/vitalinux
-        fi
-        LOGFILE="/var/log/vitalinux/${LOGFILE}"
+        [ "${EJECUTOR}" == "root" ] && \
+        DIRLOG="/var/log/vitalinux" || \
+        DIRLOG="${HOMEUSUGRAF}/.vx-logs"
+        [ ! -d "${DIRLOG}" ] && mkdir -p "${DIRLOG}"
+        LOGFILE="${DIRLOG}/${LOGFILE}"
     else
-        LOGFILE="/tmp/logfile.regenerar-perfil-usuarios.log"
+        LOGFILE="/tmp/logfile.regenerar-entorno-escritorio.log"
     fi
-    
     exec 2>&1
-    exec > >(tee -i "${LOGFILE}" )
-    
+    exec > >(tee -i "${LOGFILE}")
 }
+# 1) Preparamos la auditoria del servicio:
+log_xsession -o "${LOG}"
 
-log_xsession -o vx-regenerar-perfil-usuarios.log
-
-if test "${EJECUTOR}" != "root" ; then
-    echo "Se requiren privilegios de \"root\" para lanzar Regenerar los perfiles de los usuarios ..."
-    exit 1
+# Regeneramos el entorno de escritorio de los usuarios:
+# 2.1) Si no se pasan parámetros y lo llama el usuario root se regeneran todos los usuarios gráficos
+# 2.2) Si no se pasan parámetros y no lo llama el usuario root se regenera la del usuario gráfico actual
+# 2.3) Si se le pasan ususarios como parámetros se regeneran únicamente los de esos usuarios
+if [[ ! -z "${1}" && "${EJECUTOR}" == "root" ]] ; then
+    LISTA_USUARIOS=("${@}")
+    elif [[ "${EJECUTOR}" == "root" ]] ; then
+    LISTA_USUARIOS=($(vx-usuarios-graficos))
+else
+    LISTA_USUARIOS=("${EJECUTOR}")
 fi
 
-echo "=> $(date) - Se va a Regenerar los perfiles de los usuarios del sistema ..."
+echo "=> $(date) Se va a Regenerar los directorios del perfil del usuario: ${LISTA_USUARIOS[@]}"
 
 # 1) Comenzamos regenerando el contenido del Escritorio y resto de directorios del perfil de los usuarios
-for USUARIO in $(vx-usuarios-graficos) ; do
+for USUARIO in ${LISTA_USUARIOS[@]} ; do
     echo ":=> Sincronizando directorios del usuario: ${USUARIO}"
     HOMEUSUARIO="$(getent passwd "${USUARIO}" | cut -d":" -f6)"
-    # El directorio Escritorio se regenera a través del script vx-regenerar-entorno-escritorio-cli:
-    # BASE="/etc/skel/Escritorio/"
-    # if test -d "${BASE}" ; then
-    # 	for DIR in "Escritorio" "Desktop" "Bureau" "Schreibtisch" ; do
-    # 		if test -d "${HOMEUSUARIO}/${DIR}" ; then
-    # 			if su "${USUARIO}" \
-    # 				-c 'rsync --delete -rl '${BASE}' '${HOMEUSUARIO}'/'${DIR} \
-    # 				--login &> /dev/null ; then
-    # 				echo " --> OK: Se ha sincronizado el ${DIR} del usuario ${USUARIO} ..."
-    # 			else
-    # 				echo " --> ERROR: No se ha sincronizado el ${DIR} del usuario ${USUARIO} ..."
-    # 			fi
-    # 		fi
-    # 	done
-    # fi
     
     #BASE="$(su "${USUARIO}" -c 'mktemp -d --tmpdir vx-sincro-directorios.XXXXXXXX' --login)"
     ## Definimos los distintos nombres de los directorios del perfil en los 4 idiomas principales:
@@ -79,12 +73,17 @@ for USUARIO in $(vx-usuarios-graficos) ; do
             for DIR in ${LISTA_DIR[*]} ; do
                 # echo "=> Se va a tratar de sincronizar el directorio: \"${DIR}\""
                 if test -d "${HOMEUSUARIO}/${DIR}" ; then
-                    if su "${USUARIO}" \
-                    -c 'rsync --delete -rl '${BASE}' '${HOMEUSUARIO}'/'${DIR} \
-                    --login > /dev/null 2>&1; then
-                        echo "==> OK: Se ha sincronizado el directorio ${DIR} del usuario ${USUARIO} ..."
+                    # if su "${USUARIO}" \
+                    # -c 'rsync --delete -rl '${BASE}' '${HOMEUSUARIO}'/'${DIR} \
+                    # --login > /dev/null 2>&1; then
+                    #     echo "==> OK: Se ha sincronizado el directorio ${DIR} del usuario ${USUARIO} ..."
+                    # else
+                    #     echo "==> ERROR: No se ha sincronizado el directorio ${DIR} del usuario ${USUARIO} ..."
+                    # fi
+                    if rsync --delete -rl --chown="${USUARIO}" "${BASE}" "${HOMEUSUARIO}/${DIR}" ; then
+                        echo " => OK: Sincronizado ${HOMEUSUARIO}/${DIR} del usuario: ${USUARIO} ..."
                     else
-                        echo "==> ERROR: No se ha sincronizado el directorio ${DIR} del usuario ${USUARIO} ..."
+                        echo " => ERROR: No sincronizado ${HOMEUSUARIO}/${DIR} del usuario: ${USUARIO} ..."
                     fi
                 fi
             done
@@ -92,4 +91,22 @@ for USUARIO in $(vx-usuarios-graficos) ; do
         IFS=${SAVEIFS}
     done
     
+    # Eliminamos el registro del Albert (core.db) y sus indexaciones que pudiera existir:
+    if [ -d "/etc/skel/.config/albert" ] ; then
+        # if ! su "${USUARIO}" \
+        # -c 'rsync -ahv --delete /etc/skel/.config/albert '${DIR}'/.config' \
+        # --login &> /dev/null ; then
+        #     ERRORES=1
+        #     echo "ERROR: Problema al copiar Albert en ${DIR} ..."
+        # else
+        #     echo "OK: copiado Albert en ${DIR} ..."
+        # fi
+        if rsync -ahv --delete --chown="${USUARIO}" "/etc/skel/.config/albert" "${HOMEUSUARIO}/.config" ; then
+            echo "OK: copiado /etc/skel/.config/albert en ${HOMEUSUARIO}/.config"
+        else
+            echo "ERROR: Problema al copiar /etc/skel/.config/albert en ${HOMEUSUARIO}/.config"
+        fi
+    else
+        echo "Warning: No hay configuración de Albert Launcher"
+    fi
 done
